@rootURL = http://localhost:5224

GET {{rootURL }}/api/Orders/
Accept: application/json

###

POST {{rootURL }}/api/Orders/  
Content-Type: application/json
{
   
  "orderName": "Coffee",
  "orderDate": "2023-10-01",
  "orderStatus": "Pending"

   
}
###

GET {{rootURL }}/api/Orders/1
Accept: application/json

###