@rootURL = http://localhost:5224

GET {{rootURL }}/api/Orders/
Accept: application/json

###

POST {{rootURL }}/api/Orders/  
Content-Type: application/json
{
   
  "orderName": "Coffee",
  "orderDate": "2023-10-01",
  "orderStatus": "Pending"

   
}
###

PUT {{rootURL }}/api/Orders/11
Content-Type: application/json
{
  "orderId": "3", 
  "orderName": "Juice",
  "orderDate": "2023-10-04",
  "orderStatus": "Pending"
   
}
###